version: '3.1'

services:

  mongo:
    image: mongo:4.4.5-bionic
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27018:8081